name: BucketDisplayFix
version: '1.0'
main: acid.jacker.bucketDisplayFix.BucketDisplayFix
api-version: '1.20'
authors: [ JackerAcid ]
description: Forces inventory update for situations where client and server bucket reach do not match. (Prevents DISPLAY ghosting)
